repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^apps/api/
        args: [--line-length=88]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        files: ^apps/api/
        args: [--fix]

  # Frontend formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^apps/web/.*\.(js|jsx|ts|tsx|json|css|md)$
        args: [--write]

  # General formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^apps/web/\.next/
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]