name: Reusable Node.js Test Workflow

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      # pnpm-version removed - project uses npm
      working-directory:
        required: false
        type: string
        default: './apps/web'
      build-command:
        required: false
        type: string
        default: 'npm run build'
      test-command:
        required: false
        type: string
        default: 'npm run test'
    secrets:
      NEXT_PUBLIC_API_URL:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci

      - name: Run linting
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm run lint || true
          npm run type-check || true

      - name: Build application
        working-directory: ${{ inputs.working-directory }}
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: ${{ inputs.build-command }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ inputs.working-directory }}/coverage